/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframe;

/**
 *
 * @author DKID
 */
public class kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form kuis2
     */
    public kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dellete = new javax.swing.JButton();
        oke = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        aman = new javax.swing.JTextArea();
        harga1 = new javax.swing.JTextField();
        harga3 = new javax.swing.JTextField();
        diskon = new javax.swing.JTextField();
        harga2 = new javax.swing.JTextField();
        harga4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("==KASIR SLURRRRRR==");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(181, 31, 272, 43);

        jLabel2.setText("Harga barang1 :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 114, 116, 20);

        jLabel3.setText("Harga barang2 :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 151, 116, 20);

        jLabel4.setText("Diskon            :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 275, 114, 20);

        jLabel5.setText("Harga barang3 :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 194, 116, 20);

        jLabel6.setText("Harga barang4 :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 238, 116, 20);

        dellete.setText("Hapus");
        dellete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delleteActionPerformed(evt);
            }
        });
        getContentPane().add(dellete);
        dellete.setBounds(262, 362, 77, 29);

        oke.setText("Proses");
        oke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okeActionPerformed(evt);
            }
        });
        getContentPane().add(oke);
        oke.setBounds(138, 362, 79, 29);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(386, 362, 77, 29);

        aman.setColumns(20);
        aman.setRows(5);
        jScrollPane1.setViewportView(aman);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(24, 400, 606, 240);
        getContentPane().add(harga1);
        harga1.setBounds(171, 114, 282, 26);
        getContentPane().add(harga3);
        harga3.setBounds(174, 191, 279, 26);
        getContentPane().add(diskon);
        diskon.setBounds(174, 269, 279, 26);
        getContentPane().add(harga2);
        harga2.setBounds(174, 156, 279, 26);
        getContentPane().add(harga4);
        harga4.setBounds(174, 235, 279, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delleteActionPerformed
        harga1.setText("");
        harga2.setText("");
        harga3.setText("");
        harga4.setText("");
        diskon.setText("");

    }//GEN-LAST:event_delleteActionPerformed

    private void okeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okeActionPerformed
        int Harga1 =Integer.parseInt(harga1.getText());
        int Harga2 = Integer.parseInt(harga2.getText());
        int Harga3 = Integer.parseInt(harga3.getText());
        int Harga4 = Integer.parseInt(harga4.getText());
        int    Diskon = Integer.parseInt(diskon.getText());
        
        int totalharga;
        totalharga = Harga1 + Harga2 + Harga3 + Harga4;
        int bayar = totalharga - (totalharga * Diskon/100);
        
        aman.setText(">>Harga1 :" + Harga1 + "\n>>Harga2 :" + Harga2 + "\n>>Harga3 :" + Harga3 + "\n>>Harga4 :" + Harga4 + "\n>>Total :" + totalharga + "\n>>Pembayaran :" + bayar);
        
            

        
        
    }//GEN-LAST:event_okeActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
          dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aman;
    private javax.swing.JButton dellete;
    private javax.swing.JTextField diskon;
    private javax.swing.JTextField harga1;
    private javax.swing.JTextField harga2;
    private javax.swing.JTextField harga3;
    private javax.swing.JTextField harga4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton oke;
    // End of variables declaration//GEN-END:variables
}
