/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframe;

/**
 *
 * @author DKID
 */
public class kuis extends javax.swing.JFrame {

    /**
     * Creates new form kuis
     */
    public kuis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nilai = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        mapel = new javax.swing.JTextField();
        absen = new javax.swing.JTextField();
        gas = new javax.swing.JButton();
        print = new javax.swing.JTextField();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jframe/28large.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("---==PUNTEN==--");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(178, 16, 190, 47);

        jLabel2.setText("Nama :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(41, 112, 52, 20);

        jLabel3.setText("Absen :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 150, 55, 20);

        jLabel4.setText("Mapel :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 250, 66, 26);

        jLabel5.setText("Nilai   :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 200, 55, 26);

        nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiActionPerformed(evt);
            }
        });
        getContentPane().add(nilai);
        nilai.setBounds(120, 200, 240, 26);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(120, 100, 240, 26);

        mapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapelActionPerformed(evt);
            }
        });
        getContentPane().add(mapel);
        mapel.setBounds(120, 250, 240, 26);

        absen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absenActionPerformed(evt);
            }
        });
        getContentPane().add(absen);
        absen.setBounds(120, 150, 240, 26);

        gas.setText("GASSS");
        gas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gasActionPerformed(evt);
            }
        });
        getContentPane().add(gas);
        gas.setBounds(180, 300, 81, 29);

        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(50, 390, 440, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void mapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mapelActionPerformed

    private void absenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_absenActionPerformed

    private void nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiActionPerformed

    private void gasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gasActionPerformed
        String Nama = nama.getText() ;
    String Absen = absen.getText() ;
    String Mapel = mapel.getText();
    int Nilai = Integer.parseInt(nilai.getText());
    String kelulusan = null;
    
    if (Nilai >= 75){
      kelulusan = "==SELAMAT ANDA BISA LULUS DAN MENIKAH==";
    }
    else if (Nilai < 75){
      kelulusan = "==TINGKATKAN BELAJARMU==";
    }                                     

    else if (Nilai == 100){
        kelulusan = "==PERFECT==";
    }else if (Nilai <100){
        kelulusan = "==ANDA TERLALU PRO";
    }
    print.setText(">>Nama :" + Nama + ">>Absen :" + Absen + ">>Mapel :" + Mapel + ">>Nilai :" + Nilai + kelulusan );
    }//GEN-LAST:event_gasActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        String Nama = nama.getText() ;
        String Absen = absen.getText() ;
        String Mapel = mapel.getText();
        int Nilai = Integer.parseInt(nilai.getText());
        String kelulusan = null;

        if (Nilai >= 75){
            kelulusan = "==SELAMAT ANDA BISA LULUS DAN MENIKAH==";
        }
        else if (Nilai < 75){
            kelulusan = "==TINGKATKAN BELAJARMU==";
    }//GEN-LAST:event_printActionPerformed

    else if (Nilai == 100){
        kelulusan = "==PERFECT==";
    }else if (Nilai <100){
        kelulusan = "==ANDA TERLALU PRO";
    }
    print.setText(">>Nama :" + nama + ">>Absen :" + absen + ">>Mapel :" + mapel + ">>Nilai :" + nilai + kelulusan );
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField absen;
    private javax.swing.JButton gas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField mapel;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nilai;
    private javax.swing.JTextField print;
    // End of variables declaration//GEN-END:variables
}
