/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframe;

/**
 *
 * @author DKID
 */
public class Latihan2 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan2
     */
    public Latihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Absen = new javax.swing.JLabel();
        Kelas = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        nama1 = new javax.swing.JTextField();
        absen1 = new javax.swing.JTextField();
        alamat1 = new javax.swing.JTextField();
        kelas1 = new javax.swing.JTextField();
        y = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outhitung = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 36)); // NOI18N
        jLabel1.setText("FORMULIR OPPO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(123, 27, 602, 76);

        Nama.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Nama.setText("Nama     :");
        getContentPane().add(Nama);
        Nama.setBounds(79, 172, 110, 29);

        Absen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Absen.setText("Absen     :");
        getContentPane().add(Absen);
        Absen.setBounds(79, 224, 112, 29);

        Kelas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Kelas.setText("Kelas      :");
        getContentPane().add(Kelas);
        Kelas.setBounds(79, 273, 112, 29);

        Alamat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Alamat.setText("Alamat    :");
        getContentPane().add(Alamat);
        Alamat.setBounds(79, 322, 113, 29);
        getContentPane().add(nama1);
        nama1.setBounds(207, 177, 246, 26);
        getContentPane().add(absen1);
        absen1.setBounds(206, 229, 246, 26);
        getContentPane().add(alamat1);
        alamat1.setBounds(210, 327, 246, 26);

        kelas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelas1ActionPerformed(evt);
            }
        });
        getContentPane().add(kelas1);
        kelas1.setBounds(209, 278, 246, 26);

        y.setFont(new java.awt.Font("Wide Latin", 0, 36)); // NOI18N
        y.setText("Y.");
        y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yActionPerformed(evt);
            }
        });
        getContentPane().add(y);
        y.setBounds(210, 384, 123, 101);

        outhitung.setColumns(20);
        outhitung.setRows(5);
        jScrollPane1.setViewportView(outhitung);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 390, 370, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kelas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelas1ActionPerformed

    private void yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yActionPerformed
        String nama = nama1.getText();
        String absen = absen1.getText();
        String kelas = kelas1.getText();
        String alamat = alamat1.getText();
        
        outhitung.setText("\nNama :" + nama + "\nNomor absen :" + absen + "\nKelas : " + kelas+ "\nAlamat :" + alamat); 
    }//GEN-LAST:event_yActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Absen;
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Kelas;
    private javax.swing.JLabel Nama;
    private javax.swing.JTextField absen1;
    private javax.swing.JTextField alamat1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kelas1;
    private javax.swing.JTextField nama1;
    private javax.swing.JTextArea outhitung;
    private javax.swing.JToggleButton y;
    // End of variables declaration//GEN-END:variables
}
