/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframe;

/**
 *
 * @author DKID
 */
public class Latihan1 extends javax.swing.JFrame {
    

    /**
     * Creates new form Latihan1
     */
    public Latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kelas1 = new javax.swing.JLabel();
        nama1 = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        alamat2 = new javax.swing.JTextField();
        progres = new javax.swing.JButton();
        nama = new javax.swing.JTextField();
        kelas = new javax.swing.JTextField();
        kelas2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        alamat1 = new javax.swing.JLabel();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 16)); // NOI18N
        jLabel1.setText("--==FORMULIR NIKAH :V==--");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(126, 37, 291, 59);

        jLabel2.setText("Nama    :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(33, 155, 77, 38);

        jLabel3.setText("Alamat  :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(33, 249, 67, 38);

        kelas1.setText("Kelas     :");
        getContentPane().add(kelas1);
        kelas1.setBounds(41, 439, 67, 38);

        nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama1ActionPerformed(evt);
            }
        });
        getContentPane().add(nama1);
        nama1.setBounds(133, 382, 280, 26);

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        getContentPane().add(alamat);
        alamat.setBounds(133, 255, 280, 26);

        alamat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamat2ActionPerformed(evt);
            }
        });
        getContentPane().add(alamat2);
        alamat2.setBounds(133, 495, 280, 26);

        progres.setText("PROGRES");
        progres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progresActionPerformed(evt);
            }
        });
        getContentPane().add(progres);
        progres.setBounds(195, 317, 103, 29);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(138, 161, 279, 26);

        kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasActionPerformed(evt);
            }
        });
        getContentPane().add(kelas);
        kelas.setBounds(133, 208, 280, 26);

        kelas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelas2ActionPerformed(evt);
            }
        });
        getContentPane().add(kelas2);
        kelas2.setBounds(133, 445, 280, 26);

        jLabel5.setText("Nama    :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(41, 376, 77, 38);

        jLabel6.setText("Kelas     :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(33, 202, 85, 38);

        alamat1.setText(" Alamat   :");
        getContentPane().add(alamat1);
        alamat1.setBounds(41, 498, 76, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama1ActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void alamat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamat2ActionPerformed

    private void progresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progresActionPerformed
        String Nama = nama.getText();
        nama1.setText(Nama);
        String Kelas = kelas.getText();
        kelas2.setText(Kelas);
        String Alamat = alamat.getText();
        alamat2.setText(Alamat);
    }//GEN-LAST:event_progresActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasActionPerformed

    private void kelas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelas2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel alamat1;
    private javax.swing.JTextField alamat2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField kelas;
    private javax.swing.JLabel kelas1;
    private javax.swing.JTextField kelas2;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nama1;
    private javax.swing.JButton progres;
    // End of variables declaration//GEN-END:variables
}
